name: Test build Koboldcpp-ROCm Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of koboldcpp-rocm to test: v1.43.2-ROCm'
        default: latest
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of koboldcpp-rocm to test: v1.43.2-ROCm'
        default: latest
        required: false
        type: string

permissions:
  contents: write

jobs:
  build_libs:
    name: test ROCm Lib
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'YellowRoseCx/koboldcpp-rocm'
          ref: main 
          submodules: 'recursive'
          
      - name: Install ROCm SDK
        run: |
          curl -LO https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP.exe
          Start-Process 'AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP.exe' -ArgumentList '-install' -NoNewWindow -Wait
          echo "C:\Program Files\AMD\ROCm\5.5\bin" >> $env:GITHUB_PATH
          echo 'ROCM_PATH=C:\Program Files\AMD\ROCm\5.5' >> $env:GITHUB_ENV
          echo 'HIP_PATH=C:\Program Files\AMD\ROCm\5.5' >> $env:GITHUB_ENV
          echo "ROCM_VERSION=5.5.1" >> $env:GITHUB_ENV
          
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install Dependencies
        run: |
          python -m pip install cmake ninja
          
      - name: Install PyInstaller
        run: pip install pyinstaller psutil
        
      - name: Copy ROCm DLLs and Run PyInstaller
        run: |
          Set-Location 'D:\a\koboldcpp-rocm\koboldcpp-rocm'
          Get-Location
          copy "C:\Program Files\AMD\ROCm\5.5\bin\hipblas.dll" .\
          copy "C:\Program Files\AMD\ROCm\5.5\bin\rocblas.dll" .\
          robocopy "C:\Program Files\AMD\ROCm\5.5\bin\rocblas" .\rocblas /MIR
          curl -LO https://github.com/YellowRoseCx/koboldcpp-rocm/releases/download/v1.43.2-ROCm/gfx103132rocblasfiles.7z
          7z x gfx103132rocblasfiles.7z 
          Set-Location 'D:\a\koboldcpp-rocm\koboldcpp-rocm\rocblas\library'
          ls
